---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Content
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: contents/assets
public_path: static
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  instant_preview_command: npm run forestry:preview
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
